name: dartonic_postgres
description: PostgreSQL driver for Dartonic. Provides connectPostgres() to create a type-safe database connection.
version: 1.0.0
homepage: https://github.com/evandersondev/dartonic
repository: https://github.com/evandersondev/dartonic
topics:
  - orm
  - database
  - postgresql

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dartonic_core: ^1.0.0
  postgres: ^3.5.4

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
